@startuml
skinparam WrapWidth 600
skinparam classAttributeIconSize 0
' hide circle
skinparam linetype ortho
skinparam linetype polyline
top to bottom direction
left to right direction
skinparam componentStyle uml2

class Checks {
    -{field}_checkList: uint8
    --
    -_passCheck(check: uint8)
    -_isCheckListEmpty(): bool
    +checksEmpty() //modifier
}

@enduml
