@startuml
skinparam WrapWidth 600
skinparam classAttributeIconSize 0
' hide circle
skinparam linetype ortho
skinparam linetype polyline
top to bottom direction
left to right direction
skinparam componentStyle uml2

class Proposal {
  +<b>{field}_addrRoot: address
  +{field}_addrSmvStore: address
  +{field}_addrChange: address
  +{field}_data: ProposalData
  +{field}_results: ProposalResults
  +{field}_voteCountModel: VoteCountModel
  +{field}_inited: bool
  +{field}_commentsCounter: uint32
  ..initialData..
  +{static}_id: uint32
  --
  +constructor(title: string, totalVotes: uint128, addrClient: address, proposalType: ProposalType, specific: TvmCell, codeCrystalVotingWallet: TvmCell, codeVotingWallet: TvmCell)
  +addComment(addrReply: address, content: string)
  -_onInit()
  -_finalize(passed: bool)
  -_tryEarlyComplete(yes: uint128, no: uint128): bool, bool
  -_wrapUp()
  -_calculateVotes(yes: uint128, no: uint128): bool
  -_softMajority(yes: uint128, no: uint128): bool
  -_changeState(state: ProposalState)
}

@enduml
