export default {
  abi: {
    "ABI version": 2,
    version: "2.2",
    header: ["time", "expire"],
    functions: [
      {
        name: "constructor",
        inputs: [
          { name: "addrSmvStore", type: "address" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "totalVotes", type: "uint128" },
          { name: "addrClient", type: "address" },
          { name: "addrChange", type: "address" },
          { name: "payload", type: "cell" },
        ],
        outputs: [],
      },
      {
        name: "updateCode",
        inputs: [
          { name: "kind", type: "uint8" },
          { name: "code", type: "cell" },
        ],
        outputs: [],
      },
      { name: "wrapUp", inputs: [], outputs: [] },
      {
        name: "vote",
        inputs: [
          { name: "addrVotingWalletOwner", type: "address" },
          { name: "choice", type: "bool" },
          { name: "votes", type: "uint128" },
        ],
        outputs: [],
      },
      { name: "queryStatus", inputs: [], outputs: [] },
      {
        name: "getExt",
        inputs: [],
        outputs: [
          {
            components: [
              { name: "addr", type: "address" },
              { name: "title", type: "string" },
              { name: "description", type: "string" },
              { name: "payload", type: "cell" },
              { name: "client", type: "address" },
              { name: "state", type: "uint8" },
              { name: "start", type: "uint32" },
              { name: "end", type: "uint32" },
              { name: "votesFor", type: "uint128" },
              { name: "votesAgainst", type: "uint128" },
              { name: "totalVotes", type: "uint128" },
              { name: "addrsVotingWallet", type: "address[]" },
              { name: "commentsCounter", type: "uint32" },
            ],
            name: "data",
            type: "tuple",
          },
        ],
      },
      {
        name: "addComment",
        inputs: [
          { name: "addrReply", type: "address" },
          { name: "content", type: "string" },
        ],
        outputs: [],
      },
      {
        name: "resolveVotingWallet",
        inputs: [
          { name: "addrRoot", type: "address" },
          { name: "addrOwner", type: "address" },
        ],
        outputs: [{ name: "addrVotingWallet", type: "address" }],
      },
      {
        name: "resolveComment",
        inputs: [
          { name: "addrProposal", type: "address" },
          { name: "id", type: "uint32" },
        ],
        outputs: [{ name: "addrComment", type: "address" }],
      },
      {
        name: "resolveCommentCodeHash",
        inputs: [{ name: "addrProposal", type: "address" }],
        outputs: [{ name: "codeHashComment", type: "uint256" }],
      },
      {
        name: "_addrRoot",
        inputs: [],
        outputs: [{ name: "_addrRoot", type: "address" }],
      },
      {
        name: "_addrSmvStore",
        inputs: [],
        outputs: [{ name: "_addrSmvStore", type: "address" }],
      },
      {
        name: "_addrChange",
        inputs: [],
        outputs: [{ name: "_addrChange", type: "address" }],
      },
      { name: "_id", inputs: [], outputs: [{ name: "_id", type: "uint32" }] },
      {
        name: "_data",
        inputs: [],
        outputs: [
          {
            components: [
              { name: "addr", type: "address" },
              { name: "title", type: "string" },
              { name: "description", type: "string" },
              { name: "payload", type: "cell" },
              { name: "client", type: "address" },
              { name: "state", type: "uint8" },
              { name: "start", type: "uint32" },
              { name: "end", type: "uint32" },
              { name: "votesFor", type: "uint128" },
              { name: "votesAgainst", type: "uint128" },
              { name: "totalVotes", type: "uint128" },
              { name: "addrsVotingWallet", type: "address[]" },
              { name: "commentsCounter", type: "uint32" },
            ],
            name: "_data",
            type: "tuple",
          },
        ],
      },
      {
        name: "_results",
        inputs: [],
        outputs: [
          {
            components: [
              { name: "completed", type: "bool" },
              { name: "passed", type: "bool" },
              { name: "votesFor", type: "uint128" },
              { name: "votesAgainst", type: "uint128" },
              { name: "totalVotes", type: "uint256" },
              { name: "model", type: "uint8" },
            ],
            name: "_results",
            type: "tuple",
          },
        ],
      },
      {
        name: "_voteCountModel",
        inputs: [],
        outputs: [{ name: "_voteCountModel", type: "uint8" }],
      },
      {
        name: "_inited",
        inputs: [],
        outputs: [{ name: "_inited", type: "bool" }],
      },
      {
        name: "_commentsCounter",
        inputs: [],
        outputs: [{ name: "_commentsCounter", type: "uint32" }],
      },
    ],
    data: [{ key: 1, name: "_id", type: "uint32" }],
    events: [],
    fields: [
      { name: "_pubkey", type: "uint256" },
      { name: "_timestamp", type: "uint64" },
      { name: "_constructorFlag", type: "bool" },
      { name: "_codeComment", type: "cell" },
      { name: "_codeVotingWallet", type: "cell" },
      { name: "_checkList", type: "uint8" },
      { name: "_addrRoot", type: "address" },
      { name: "_addrSmvStore", type: "address" },
      { name: "_addrChange", type: "address" },
      { name: "_id", type: "uint32" },
      {
        components: [
          { name: "addr", type: "address" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "payload", type: "cell" },
          { name: "client", type: "address" },
          { name: "state", type: "uint8" },
          { name: "start", type: "uint32" },
          { name: "end", type: "uint32" },
          { name: "votesFor", type: "uint128" },
          { name: "votesAgainst", type: "uint128" },
          { name: "totalVotes", type: "uint128" },
          { name: "addrsVotingWallet", type: "address[]" },
          { name: "commentsCounter", type: "uint32" },
        ],
        name: "_data",
        type: "tuple",
      },
      {
        components: [
          { name: "completed", type: "bool" },
          { name: "passed", type: "bool" },
          { name: "votesFor", type: "uint128" },
          { name: "votesAgainst", type: "uint128" },
          { name: "totalVotes", type: "uint256" },
          { name: "model", type: "uint8" },
        ],
        name: "_results",
        type: "tuple",
      },
      { name: "_voteCountModel", type: "uint8" },
      { name: "_inited", type: "bool" },
      { name: "_commentsCounter", type: "uint32" },
    ],
  },
  image:
    "te6ccgECUAEADkYAAgE0AwEBAcACAEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAgaK2zVPBAQkiu1TIOMDIMD/4wIgwP7jAvILTAYFTgLg7UTQ10nDAfhmjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+Gkh2zzTAAGfgQIA1xgg+QFY+EL5EPKo3tM/AfhDIbnytCD4I4ED6KiCCBt3QKC58rT4Y9MfAfgjvPK50x8B2zzyPC0HA1LtRNDXScMB+GYi0NMD+kAw+GmpOADcIccA4wIh1w0f8rwh4wMB2zzyPEtLBwIoIIIQYxBAGbvjAiCCEHoMAEq74wIMCAM8IIIQdA+5RrrjAiCCEHazAzW64wIgghB6DABKuuMCCwoJA4gw+Eby4Ez4Qm7jACGT1NHQ3vpA1NHQ+kDR2zwhjh8j0NMB+kAwMcjPhyDOcc8LYQHIz5PoMAEqzs3JcPsAkTDi4wDyAEkiQAFOMNHbPPhPIY4bjQRwAAAAAAAAAAAAAAAAPazAzWDIzs7JcPsA3vIASQFOMNHbPPhNIY4bjQRwAAAAAAAAAAAAAAAAPQPuUaDIzs7JcPsA3vIASQRQIIIQJoQVYrvjAiCCEDJDfKe74wIgghBPUapcu+MCIIIQYxBAGbvjAjkyIw0EUCCCEFWDHtW64wIgghBYBRmJuuMCIIIQYWmQtrrjAiCCEGMQQBm64wIVERAOAyYw+Eby4Ez4Qm7jANHbPDDbPPIASQ88ASTbPPhJyM+FCM6Ab89AyYBA+wAZAaQw0ds8+FEhjkaL3AAAAAAAAAAAAAAAABjIzgHIz5OFpkLaAW8tXsDOzMzMVYDIzssHyx/LH8t/y39VIMjLfwFvIgLLH/QAyx/Nzc3JcPsA3vIASQM4MPhG8uBM+EJu4wAhk9TR0N76QNTR2zww2zzyAEkSPAP+aKb+YIIQC+vCAL7y4GX4SY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcF8tBk+Cj4Vds8AvhJVQIg+QDIz4oAQMv/yM+FiM8TjQSQF9eEAAAAAAAAAAAAAAAAAAHAzxYh2zzMz4NVIMjPkdM2O/rOWcjOzEIUEwAqzc3JcPsA+FWktR/4dfhR+FVvXPhxADTQ0gABk9IEMd7SAAGT0gEx3vQE9AT0BNFfAwM+MPhG8uBM+EJu4wAhk9TR0N76QNIA03/R2zww2zzyAEkWPAK4aKb+YIIQF9eEAL7y4GX4TVUC2zxwIPhRbxtvEI4lcJgg+FFvG28QuY4XIPhRbxtvEYAg9A7ysiTHBZJ/Mt6ktQfoMJIwf+KOgN5fBPhJyM+FCM6Ab89AyYBA+wAiFwG2IfhJxwWOG/gj+FFvFrmUMIEBLJ34I/hRbxe8lDCBAS3e4pMwgGTiIMIAji8i+El/yM+FgMoAc89Azo0FkBfXhAAAAAAAAAAAAAAAAAAAPxQGr8DPFst/yXP7ABgBqI5PIvhJf8jPhYDKAHPPQM6NBZAX14QAAAAAAAAAAAAAAAAAACnrdN3AzxbLf8lz+wAjniL4USBvGFigtX9vWPhxniL4USBvGVigtX9vWfhx4uLbPBkDJnAg+CP4UW8XvI6AjoDiAY6A3jAfHRoBFPhRc29V+HEg2zwbAbp/IfhRbxj4UW8Z+FFvGvhTbwb4ciCRdJF14vhRAW9V+HGOOvhRbxP4UW8U+FD4TcjPhYjOjQSQX14QAAAAAAAAAAAAAAAAAADAzxZVIMjPkdily7LLH87Mzclw+wAcAHqOOvhRbxP4UW8U+FD4TcjPhYjOjQSQX14QAAAAAAAAAAAAAAAAAADAzxZVIMjPkZ4G8A7LH87Mzclw+wDiARj4UW8Y+FFvGds8bCIeAEhwIFUCpwK1f/hRbxq8k1t/IJ8ipwK1f/hRbxq+k1t/cN7ibBIBGn8y+FFvGPhRbxnbPDEgAQTbPCEAWAFx+FFvGnqpBKC1f1j4UW8aqwD4UW8aeqkEobV/qLV/+FFvGqsAqQSgtX++AW5wyMv/cG2AQPRDAXFYgED0Fsj0AMkByM74S9AByds8yM+EgPQA9ADPgcn5AHDIz4ZAygfL/8nQQwRQIIIQM//Ui7rjAiCCEDWKi5C64wIgghBIOkVeuuMCIIIQT1GqXLrjAjEnJiQDvDD4RvLgTPhCbuMA0ds8IY5GI9DTAfpAMDHIz4cgznHPC2EByM+TPUapcgFvLV7AzszMzFWAyM7LB8sfyx/Lf8t/VSDIy38BbyICyx/0AMsfzc3NyXD7AJEw4uMA8gBJJUAABPhRAVAw0ds8+FMhjhyNBHAAAAAAAAAAAAAAAAAyDpFXoMjOywfJcPsA3vIASQT+MPhCbuMA+EbycyGT1NHQ3vpA1NTTf9TR0PpA1NHQ+kDU0fhBiMjPjits1szOyds8IG7y0GQgbvJ/0PpAMPhJIccF8uBk+G1VBfhuAfhv+FH4KG9QIPhxVQRvUSD4cVUDb1Ig+HEBb1Mg+HEBb1Qg+HH4I29W+HH4I4IICTqAoC1PKigB/rUf+FEBb1cg+HFxb1Ug+HEBb1r4cXL4c3D4Tn/Iz4WAygBzz0DOjQWQL68IAAAAAAAAAAAAAAAAAAA/mU1FwM8WywfJcPsAcvhOf8jPhYDKAHPPQM6NBZAvrwgAAAAAAAAAAAAAAAAAAD+ZTUXAzxbLB8lw+wD4UW8UyM+FiM4pAaKNBJAX14QAAAAAAAAAAAAAAAAAAMDPFvhRyM+QqB0odgFvLV7AzszMzFWAyM7LB8sfyx/Lf8t/VSDIy38BbyICyx/0AMsfzc3NyXD7ANs88gA8AhjQIIs4rbNYxwWKiuIrLAEK103Q2zwsAELXTNCLL0pA1yb0BDHTCTGLL0oY1yYg10rCAZLXTZIwbeICFu1E0NdJwgGOgOMNLkkD/nDtRND0BYj4aoj4a3D4bI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPhtjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+G6NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAROTi8C+vhvcSGAQPQOk9cLH5Fw4vhwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiF8gjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcF9gbW8CcG8N+HFwX1BvBvhycPhzcPh0cPh1gED0DvK9TjAAHNcL//hicPhjcPh0cPh1AVAw0ds8+FUhjhyNBHAAAAAAAAAAAAAAAAAs//Ui4MjOyx/JcPsA3vIASQRQIIIQJofbgrrjAiCCECesRYe64wIgghAswacOuuMCIIIQMkN8p7rjAjc2NTMDkDD4RvLgTPhCbuMAIZPU0dDe+kDR2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAALJDfKeM8Wy//JcPsAkTDi4wDyAEk0QAEWyM74StAByds8+QBDAVAw0ds8+FQhjhyNBHAAAAAAAAAAAAAAAAArMGnDoMjOygDJcPsA3vIASQFOMNHbPPhOIY4bjQRwAAAAAAAAAAAAAAAAKesRYeDIzs7JcPsA3vIASQMmMPhG8uBM+EJu4wDR2zww2zzyAEk4PABe+FFvFfhJf8jPhYDKAHPPQM6NBIAAAAAAAAAAAAAAAAAAB9eGBcDPFssHyYBA+wAEUCCCEA8RwKK64wIgghAcrSaGuuMCIIIQHThHZLrjAiCCECaEFWK64wJIPzs6AW4w0ds8+FIhjiuNBHAAAAAAAAAAAAAAAAApoQVYoMjOAW8mXlDKAMoAy3/Lf8v/ywfJcPsA3vIASQM4MPhG8uBM+EJu4wDTByHCAvLQSdTR2zww2zzyAEk9PAD2+FX4VPhT+FL4UfhQ+E/4TvhN+Ez4S/hK+EP4QsjL/8s/z4PMzMsHzlVwyM5VYMjOyx8Bby1ewIARYsjOzMzMVcDIzssHyx/LH8t/y39VYMjLfwFvIgLLH/QAyx8BbyZeUMoAygDLf8t/y//LB8sHygDLH83Nzc3Nye1UAXz4SfhOxwXy4GQhjhEhwAKcIPhqcoQHovhMsPhs3pwg+GtxhAei+Eyw+GziW/hPyM+FCM6Ab89AyYBA+wDbPD4APPhMwAD4VLOwjhN/+HT4UW8W+CO7l/hRcm9V+HHe3gOCMPhG8uBM+EJu4wAhk9TR0N76QNMf0ds8IY4fI9DTAfpAMDHIz4cgznHPC2EByM+ScrSaGs7NyXD7AJEw4uMA8gBJQUAAKO1E0NP/0z8x+ENYyMv/yz/Oye1UAR7bPPkAcMjPhkDKB8v/ydBCAVpwyMv/cG2AQPRDAcjLH3FYgED0Q8j0AMkByM74StAByds8yM+EgPQA9ADPgclDAhYhizits1jHBYqK4kVEAQgB2zzJRgEmAdTUMBLQ2zzIz44rbNYSzM8RyUYBZtWLL0pA1yb0BNMJMSDXSpHUjoDiiy9KGNcmMAHIz4vSkPQAgCDPCwnPi9KGzBLMyM8RzkcBBIgBTgFQMNHbPPhQIY4cjQRwAAAAAAAAAAAAAAAAI8RwKKDIzssfyXD7AN7yAEkB/u1E0NP/0z/TADHU1NMH+kDU0dD6QNTR0PpA0x/U0dD6QNTU1NTR0PpA0wchwgny0EnTH9Mf03/Tf9TR0NN/0x/0BFlvAgHTH1XAbw0B0gDSANN/03/T/9MHIcIG8tBJVVBvBgHTByHCBvLQSdIA0x/R+HX4dPhz+HL4cfhw+G9KABz4bvht+Gz4a/hq+GP4YgAK+Eby4EwCCvSkIPShTk0AFHNvbCAwLjUzLjAAAAAMIPhh7R7Z",
};
