@startuml
skinparam WrapWidth 600
skinparam classAttributeIconSize 0
' hide circle
skinparam linetype ortho
skinparam linetype polyline
top to bottom direction
left to right direction
skinparam componentStyle uml2


interface IClient {
    +onProposalNotPassed(addrProposal: address, proposalType: ProposalType, specific: TvmCell)
    +onProposalPassed(addrProposal: address, proposalType: ProposalType, specific: TvmCell)
    +onProposalDeployed(data: ProposalData)
}

@enduml
