@startuml
skinparam WrapWidth 600
skinparam classAttributeIconSize 0
' hide circle
skinparam linetype ortho
skinparam linetype polyline
top to bottom direction
left to right direction
skinparam componentStyle uml2


interface IProposal {
    +vote(addrVotingWalletOwner: address, choice: bool, votes: uint128)
    +queryStatus()
    +wrapUp()
    ..getters..
    +getExt(): ProposalData
}

@enduml
