@startuml
skinparam WrapWidth 600
skinparam classAttributeIconSize 0
' hide circle
skinparam linetype ortho
skinparam linetype polyline
top to bottom direction
left to right direction
skinparam componentStyle uml2


interface ISmvRootStore {
    +setVotingWalletCode(code: TvmCell)
    +setProposalCode(code: TvmCell)
    +setCommentCode(code: TvmCell)
    +queryCode(kind: ContractCode)
}

@enduml
