@startuml
skinparam WrapWidth 600
skinparam classAttributeIconSize 0
' hide circle
skinparam linetype ortho
skinparam linetype polyline
top to bottom direction
left to right direction
skinparam componentStyle uml2


interface ITokensReceivedCallback {
    +tokensReceivedCallback(token_wallet: address, token_root: address, amount: uint128, sender_public_key: uint256, sender_address: address, sender_wallet: address, original_gas_to: address, updated_balance: uint128, payload: TvmCell)
}

@enduml
